server:
  port: 8030
spring:
  datasource:
      username: chris
      password: 123123
      url: 'jdbc:mysql://prontera/account?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false'
#      max-active: 5
#      max-idle: 5
#      min-evictable-idle-time-millis: 200
#      min-idle: 3
#      initial-size: 3
#      driver-class-name: com.mysql.jdbc.Driver
#      remove-abandoned: true
  rabbitmq:
    host: prontera
    username: chris
    password: 123123
    virtual-host: prontera
  application:
    name: 'account'
mybatis:
  type-handlers-package: 'com.github.**.type.handler'
  mapper-locations: 'classpath*:mapper/**/*Mapper.xml'
  type-aliases-package: 'com.github.**.domain'
eureka:
  client:
    service-url:
      default-zone: 'peer1:8761/eureka/,peer2:8762/eureka/'
  instance:
    metadata-map:
      cluster: prontera
    prefer-ip-address: false
