server:
  port: ${port:${PORT:8762}}
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false
    metadata-map:
      cluster: prontera
  client:
    service-url:
      defaultZone: 'http://peer1:8763/eureka/'
    fetch-registry: true
    register-with-eureka: true
  server:
    renewal-percent-threshold: '0.8'
spring:
  application:
    name: 'registry'
