## SERVER
server:
  port: 8000
## GENERAL
spring:
  application:
    name: gateway
## EUREKA
eureka:
  client:
    service-url:
      default-zone: 'http://www.payon.com:8761/eureka/,http://www.payon.com:8762/eureka/,http://www.payon.com:8763/eureka/'
## ZUUL
