server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: 'peer1:8761/eureka/,peer2:8762/eureka/'
  instance:
    metadata-map:
      cluster: prontera
    prefer-ip-address: false
spring:
  application:
    name: payment
  rabbitmq:
    host: localhost
    username: chris
    password: 123123
    virtual-host: prontera
    listener:
      retry:
        enabled: true
#    template:
#      retry:
#        enabled: false

