server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: 'http://www.payon.com:8761/eureka/,http://www.payon.com:8762/eureka/'
  instance:
    metadata-map:
      cluster: prontera
spring:
  application:
    name: payment
